# Generated by Django 5.1.1 on 2024-10-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_review_created_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'brand', 'price'], name='main_produc_categor_ae3af6_idx'),
        ),
    ]
